### ISSUE TITLE
Unable to npm install (Run in Browser (Frontend Questions)

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/inquirer-gui#250]
Using node.js version v14.15.1, I am unable to npm install, getting
![image](https://user-images.githubusercontent.com/40032066/119658418-68716600-be2d-11eb-8b29-0980a64de81d.png)

**Comment by rimasirich** [comment]
@MichaelBaySAP Check your npm configuration. Due to the response you get, it seems that the registry is configured to nexus ;)
