### ISSUE TITLE
Upgrade vuetify to 3.0 or above

### ISSUE THREAD

**Issue by LucyGit** [SAP/inquirer-gui#567]
There are security issue in vuetify 2.* when we white source scans it.
Can inquirer-gui upgrading vuetify to 3.0 verison or above

**Comment by joshvanallen** [comment]
It might be worth closing this now that the `master` branch is on Vuetify 3 + Vue 3 @veredcon

**Comment by veredcon** [comment]
@LucyGit - @joshvanallen is right, thank you for the notification! master is updated with vue3 therefore closing this issue.
