### ISSUE TITLE
Use Lerna or Nx to help manage the repository structure and dependencies

### ISSUE THREAD

**Issue by joshvanallen** [SAP/inquirer-gui#650]
Hey all! 
As part of the Vue3 migration effort, it felt that Lerna or Nrwl's NX monorepo tooling could help improve the developer experience here as it seems there's now two applications, a core library, and optional additional publishable libraries with all sharing dependencies. 

Curious of other's opinions on the matter.

**Comment by veredcon** [comment]
Hey Josh!
You are absolutely right. Now that master has been updated and I manually published all artifacts I'm ready to work on converting this repo to a mono-repo using lerna, update the dependencies, scripts, structure, circleci etc. 
If you have any tips/ good references it would be great.. I hope to make a good progress soon:)
Thank you for your insights!

**Comment by veredcon** [comment]
The repo is now managed with lerna as a monorepo.
