### ISSUE TITLE
'Confirm' question - should undefined answer be supported?

### ISSUE THREAD

**Issue by tomer-epstein** [SAP/inquirer-gui#7]
yeoman cli supports not answering a'confirm' question.
in this case the answer is 'undefined'.
should we align with the cli, so the user won't miss functionality?

**Comment by idoprz** [comment]
I think it should be like the cli. do  you see any reason not?

**Comment by tomer-epstein** [comment]
Agree.

**Comment by perspectivus1** [comment]
I verified and it is impossible to not answer a confirm-type question in inquirer CLI.

**Comment by tomer-epstein** [comment]
So, how do we handle generator-generator same behavior as cli?
